### ISSUE TITLE
No test configuration file found!

### ISSUE THREAD

**Issue by acgetchell** [gotgenes/gtestctest-sandbox#1]
Thanks very much for this sample! I've been puzzling over this myself.

running `ctest` gives;

---

No test configuration file found!

---

ctest version 2.8.12.1
Usage

  ctest [options]

**Comment by gotgenes** [comment]
Hi @acgetchell. I'm not able to reproduce this issue (I'm running 2.8.12 instead of 2.8.12.1). Have you been able to resolve this?
